### ISSUE TITLE
Errors for doing the MoE Gate Fine-tuning after the moe.py..

### ISSUE THREAD

**Issue by SOSONAGI** [mzbac/mlx-moe#1]
Hello,

I really appreciate that you share this wonderful repos for moe!

I've tried many times for Fine-tuning after merge moe (moe.py) but, i still got same errors like below :

```CLI
(mlxmoe) soonde17@sosohajalabui-MacBookPro mlx-moe % python quantize.py --model mlx_moe -q
[INFO] Loading
Traceback (most recent call last):
  File "/Users/soonde17/anaconda3/envs/mlxmoe/mlx-moe/quantize.py", line 92, in <module>
    convert(**vars(args))
  File "/Users/soonde17/anaconda3/envs/mlxmoe/mlx-moe/quantize.py", line 60, in convert
    model, tokenizer = load(model_path)
  File "/Users/soonde17/anaconda3/envs/mlxmoe/mlx-moe/utils.py", line 29, in load
    model = load_model(model_path)
  File "/Users/soonde17/anaconda3/envs/mlxmoe/mlx-moe/utils.py", line 71, in load_model
    model.load_weights(list(weights.items()))
  File "/Users/soonde17/anaconda3/envs/mlxmoe/lib/python3.10/site-packages/mlx/nn/layers/base.py", line 154, in load_weights
    raise ValueError(f"Missing parameters: {missing}.")
ValueError: Missing parameters: model.layers.22.block_sparse_moe.experts.3.w2.weight model.layers.11.block_sparse_moe.experts.2.
```

I put the model 

```CLI
EXPERT_MODEL_PATHS = [
    "mistralai/Mistral-7B-Instruct-v0.2",
    "sosoai/hansoldeco-Mistral-7B-Instruct-v0.2",
]
```

I thought the reason for above issues happened because of not a instruct model and i've made own model with instruct but still didn't work.

also, checked the model layers but, there was nothing wrong with moe.py in def update_weights..

Could you please help me for above issues?

Really appreciate for repos again.

**Comment by mzbac** [comment]
I think in the current script, if configured to have 4 local experts but you only provided two models, it caused missing weight in the model. You need to change the config [here](https://github.com/mzbac/mlx-moe/blob/main/moe.py#L70-L77) to match the number of models you provided. Also, I don't think it will work with merging 2 models as there may be an issue with the topk of 2 in the MOE layer. So your best bet would be to have 3 experts and select 2 if you want to reduce the model size.
